### ISSUE TITLE
FormatException: Trying to read yyyy from 1999 at position 0

### ISSUE THREAD

**Issue by binSaed** [dart-lang/i18n#36]
### Code
`print(intl.DateFormat('yyyy').parse('1999'));`

### intl version
```
  intl:
    dependency: transitive
    description:
      name: intl
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.17.0"
```

### Exception
`I/flutter (21756):  FormatException: Trying to read yyyy from 1999 at position 0`
