### ISSUE TITLE
not working with angular dart 5

### ISSUE THREAD

**Issue by zreptil** [dart-lang/i18n#507]
At my current project the @i18n-annotations in the template-files are not extracted when building the app and so no string of the files shows up in the arb-file. The project uses the following pubspec.yaml:

```
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_components: ^0.9.1
  intl: ^0.15.7
  crypto: ^2.0.6

dev_dependencies:
  build_runner: ^0.10.3
  build_web_compilers: ^0.4.0+4
  sass_builder: ^2.0.1
  intl_translation: ^0.17.0
```

Are there any known issues with versions of any of the dependencies? I also tried build_runner 1.0.0, but the rest of my project is not happy with this, so i need to stay at 0.10.3.
