### ISSUE TITLE
intl_translation: bump analyzer. Flutter 3.16.0

### ISSUE THREAD

**Issue by yehorh** [dart-lang/i18n#746]
**Describe the bug**

```
Analyzer language version: 3.1.0
SDK language version: 3.2.0

Please update to the latest `analyzer` version (6.3.0) by running
`flutter packages upgrade`.

If you are not getting the latest version by running the above command, you
can try adding a constraint like the following to your pubspec to start
diagnosing why you can't get the latest version:

dev_dependencies:
  analyzer: ^6.3.0
```

```
Because intl_translation 0.18.2 depends on analyzer ^5.2.0 and no versions of intl_translation match >0.18.2 <0.19.0, intl_translation ^0.18.2 requires analyzer ^5.2.0.
So, because car depends on both intl_translation ^0.18.2 and analyzer ^6.3.0, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on analyzer: flutter pub add dev:analyzer:^5.13.0
```

**System info**
`flutter doctor `
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.0, on macOS 14.1.1 23B81 darwin-arm64, locale en-UA)
```

`pubspec.yaml`
```
dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.6
  drift_dev: ^2.13.1
  flutter_gen_runner: ^5.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  intl_translation: ^0.18.2
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
```
